
name: Make and Test

on: [push]

jobs:
  build:
    name: Make and Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make bin/keyread
        run: make bin/keyread
      - name: make bin/preprocessor
        run: make bin/preprocessor
      - name: make bin/scraper
        run: make bin/scraper
      - name: make bin/suprem
        run: make bin/suprem
      - name: make bin/systest-keyread
        run: make bin/systest-keyread
      - name: make bin/systest-preprocessor
        run: make bin/systest-preprocessor
      - name: make bin/systest-scraper
        run: make bin/systest-scraper
      - name: make bin/systest-suprem
        run: make bin/systest-suprem
