
name: Make and Test

on: [push]

jobs:
  a:
    name: Keyread
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make bin/keyread
        run: make bin/keyread
      - name: make systest-keyread
        run: make systest-keyread
  b:
    name: Preprocessor
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make bin/preprocessor
        run: make bin/preprocessor
      - name: make systest-preprocessor
        run: make systest-preprocessor
