
name: Make and Test

on: [push]

jobs:
  keyread:
    name: Keyread
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install yacc and lex
        run: sudo apt-get install bison flex
      - name: make bin/keyread
        run: make bin/keyread
      - name: make systest-keyread
        run: make systest-keyread
  preprocessor:
    name: Preprocessor
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make bin/preprocessor
        run: make bin/preprocessor
      - name: make systest-preprocessor
        run: make systest-preprocessor
  scraper:
    name: Scraper
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make bin/scraper
        run: make bin/scraper
      - name: make systest-scraper
        run: make systest-scraper
  suprem:
    name: Suprem
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install yacc
        run: sudo apt-get install bison
      - name: make bin/suprem
        run: make bin/suprem
      - name: make systest-suprem
        run: make systest-suprem
